import { Interests, Regions } from "../../constants";

export const DESTINATIONS = [
	{
		id: 0,
		region: Regions.JAVA,
		categories: [Interests.ARTS],
		title: "Borobudur Temple",
		imageSrc: "/destinations/borobudur.png",
	},
	{
		id: 1,
		region: Regions.JAVA,
		categories: [Interests.NATURE, Interests.RECREATION],
		title: "Bromo Tengger Semeru",
		imageSrc: "/destinations/bromo.png",
	},
	{
		id: 2,
		region: Regions.NUSA_TENGGARA,
		categories: [Interests.NATURE, Interests.RECREATION],
		title: "Wae Rebo",
		imageSrc: "/destinations/wae_rebo.png",
	},
	{
		id: 3,
		region: Regions.JAVA,
		categories: [Interests.NATURE, Interests.RECREATION],
		title: "Thousand Islands",
		imageSrc: "/destinations/thousand_islands.png",
	},
	{
		id: 4,
		region: Regions.JAVA,
		categories: [Interests.NATURE, Interests.RECREATION],
		title: "Tanjung Lesung",
		imageSrc: "/destinations/tanjung_lesung.png",
	},
	{
		id: 5,
		region: Regions.NUSA_TENGGARA,
		categories: [Interests.RECREATION],
		title: "Mandalika",
		imageSrc: "/destinations/mandalika.png",
	},
	{
		id: 6,
		region: Regions.JAVA,
		categories: [Interests.ARTS],
		title: "Borobudur Temple",
		imageSrc: "/destinations/borobudur.png",
	},
	{
		id: 7,
		region: Regions.JAVA,
		categories: [Interests.NATURE, Interests.RECREATION],
		title: "Bromo Tengger Semeru",
		imageSrc: "/destinations/bromo.png",
	},
	{
		id: 8,
		region: Regions.NUSA_TENGGARA,
		categories: [Interests.NATURE, Interests.RECREATION],
		title: "Wae Rebo",
		imageSrc: "/destinations/wae_rebo.png",
	},
	{
		id: 9,
		region: Regions.JAVA,
		categories: [Interests.NATURE, Interests.RECREATION],
		title: "Thousand Islands",
		imageSrc: "/destinations/thousand_islands.png",
	},
	{
		id: 10,
		region: Regions.JAVA,
		categories: [Interests.NATURE, Interests.RECREATION],
		title: "Tanjung Lesung",
		imageSrc: "/destinations/tanjung_lesung.png",
	},
	{
		id: 11,
		region: Regions.NUSA_TENGGARA,
		categories: [Interests.RECREATION],
		title: "Mandalika",
		imageSrc: "/destinations/mandalika.png",
	},
];
