import { Interests, Regions } from "../../constants";

import { BookingsType } from "../../constants";

export const BOOKINGS: BookingsType[] = [
	{
		id: 0,
		imageSrc: "/trips/labuan_bajo.webp",
		categories: [Interests.NATURE, Interests.RECREATION],
		region: Regions.NUSA_TENGGARA,
		title: "Labuan Bajo",
		rating: 4.9,
		reviews: 1125,
		days: 4,
		price: 5000000,
		trending: true,
	},
	{
		id: 1,
		imageSrc: "/trips/cape_kri.jpeg",
		categories: [Interests.NATURE, Interests.RECREATION],
		region: Regions.PAPUA,
		title: "Cape Kri",
		rating: 5.0,
		reviews: 125,
		days: 5,
		price: 10000000,
	},
	{
		id: 2,
		imageSrc: "/trips/gang_pendopo.jpeg",
		categories: [Interests.NATURE],
		region: Regions.KALIMANTAN,
		title: "Gang Pendopo",
		rating: 4.5,
		reviews: 505,
		days: 3,
		price: 3000000,
	},
	{
		id: 3,
		imageSrc: "/trips/labuan_bajo.webp",
		categories: [Interests.NATURE, Interests.RECREATION],
		region: Regions.NUSA_TENGGARA,
		title: "Labuan Bajo",
		rating: 4.9,
		reviews: 1125,
		days: 4,
		price: 5000000,
		trending: true,
	},
	{
		id: 4,
		imageSrc: "/trips/cape_kri.jpeg",
		categories: [Interests.NATURE, Interests.RECREATION],
		region: Regions.PAPUA,
		title: "Cape Kri",
		rating: 5.0,
		reviews: 125,
		days: 5,
		price: 10000000,
	},
	{
		id: 5,
		imageSrc: "/trips/gang_pendopo.jpeg",
		categories: [Interests.NATURE],
		region: Regions.KALIMANTAN,
		title: "Gang Pendopo",
		rating: 4.5,
		reviews: 505,
		days: 3,
		price: 3000000,
	},
	{
		id: 6,
		imageSrc: "/trips/labuan_bajo.webp",
		categories: [Interests.NATURE, Interests.RECREATION],
		region: Regions.NUSA_TENGGARA,
		title: "Labuan Bajo",
		rating: 4.9,
		reviews: 1125,
		days: 4,
		price: 5000000,
		trending: true,
	},
	{
		id: 7,
		imageSrc: "/trips/cape_kri.jpeg",
		categories: [Interests.NATURE, Interests.RECREATION],
		region: Regions.PAPUA,
		title: "Cape Kri",
		rating: 5.0,
		reviews: 125,
		days: 5,
		price: 10000000,
	},
	{
		id: 8,
		imageSrc: "/trips/gang_pendopo.jpeg",
		categories: [Interests.NATURE],
		region: Regions.KALIMANTAN,
		title: "Gang Pendopo",
		rating: 4.5,
		reviews: 505,
		days: 3,
		price: 3000000,
	},
	{
		id: 9,
		imageSrc: "/trips/bromo.jpeg",
		categories: [Interests.NATURE],
		region: Regions.JAVA,
		title: "Bromo",
		rating: 5.0,
		reviews: 3024,
		days: 3,
		price: 3000000,
	},
];
