import { Genres } from "../../constants";
import { ProductCardProps } from "../../../components/ProductCard/constants";

export const PRODUCTS: ProductCardProps[] = [
	{
		id: 0,
		title: "Batik Roll Pattern DIY Kit",
		imageSrc: "/shop/batik.png",
		rating: 4.8,
		reviews: 559,
		price: 249000,
		genres: [Genres.FASHION, Genres.DIY_KITS],
	},
	{
		id: 1,
		title: "Krispang Kite - Aloe Vera Chips",
		imageSrc: "/shop/krispang.png",
		rating: 5,
		reviews: 409,
		price: 7000,
		genres: [Genres.CULINARY],
	},
	{
		id: 2,
		title: "Bawang Goreng Sumenep",
		imageSrc: "/shop/bawang.png",
		rating: 5,
		reviews: 1592,
		price: 49900,
		genres: [Genres.CULINARY],
	},
	{
		id: 3,
		title: "Batik Seno",
		imageSrc: "/shop/seno.png",
		rating: 4.2,
		reviews: 252,
		price: 374900,
		genres: [Genres.FASHION, Genres.CRAFTS],
	},
	{
		id: 4,
		title: "Batik Roll Pattern DIY Kit",
		imageSrc: "/shop/batik.png",
		rating: 4.8,
		reviews: 559,
		price: 249000,
		genres: [Genres.FASHION, Genres.DIY_KITS],
	},
	{
		id: 5,
		title: "Krispang Kite - Aloe Vera Chips",
		imageSrc: "/shop/krispang.png",
		rating: 5,
		reviews: 409,
		price: 7000,
		genres: [Genres.CULINARY],
	},
	{
		id: 6,
		title: "Bawang Goreng Sumenep",
		imageSrc: "/shop/bawang.png",
		rating: 5,
		reviews: 1592,
		price: 49900,
		genres: [Genres.CULINARY],
	},
	{
		id: 7,
		title: "Batik Seno",
		imageSrc: "/shop/seno.png",
		rating: 4.2,
		reviews: 252,
		price: 374900,
		genres: [Genres.FASHION, Genres.CRAFTS],
	},
];
